### ISSUE TITLE
Read the instructions

### ISSUE THREAD

**Issue by vtwoptwo** [IERoboticsClub/botzo#1]
https://www.instructables.com/GoodBoy-3D-Printed-Arduino-Robot-Dog/

**Comment by GRINGOLOCO7** [comment]
https://docs.google.com/document/d/1nHD-ojCTJDxqRnDAriQrPQ2tUhopTTEXiX9av5areTY/edit

**Comment by GRINGOLOCO7** [comment]
We decided to start by following the instructions and build our Botzo V1. so then we can implement a better version
